require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AnimalesController do

  def mock_animal(stubs={})
    @mock_animal ||= mock_model(Animal, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all animales as @animales" do
      Animal.stub(:all) { [mock_animal] }
      get :index
      assigns(:animales).should eq([mock_animal])
    end
  end

  describe "GET show" do
    it "assigns the requested animal as @animal" do
      Animal.stub(:find).with("37") { mock_animal }
      get :show, :id => "37"
      assigns(:animal).should be(mock_animal)
    end
  end

  describe "GET new" do
    it "assigns a new animal as @animal" do
      Animal.stub(:new) { mock_animal }
      get :new
      assigns(:animal).should be(mock_animal)
    end
  end

  describe "GET edit" do
    it "assigns the requested animal as @animal" do
      Animal.stub(:find).with("37") { mock_animal }
      get :edit, :id => "37"
      assigns(:animal).should be(mock_animal)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created animal as @animal" do
        Animal.stub(:new).with({'these' => 'params'}) { mock_animal(:save => true) }
        post :create, :animal => {'these' => 'params'}
        assigns(:animal).should be(mock_animal)
      end

      it "redirects to the created animal" do
        Animal.stub(:new) { mock_animal(:save => true) }
        post :create, :animal => {}
        response.should redirect_to(animal_url(mock_animal))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved animal as @animal" do
        Animal.stub(:new).with({'these' => 'params'}) { mock_animal(:save => false) }
        post :create, :animal => {'these' => 'params'}
        assigns(:animal).should be(mock_animal)
      end

      it "re-renders the 'new' template" do
        Animal.stub(:new) { mock_animal(:save => false) }
        post :create, :animal => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested animal" do
        Animal.stub(:find).with("37") { mock_animal }
        mock_animal.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :animal => {'these' => 'params'}
      end

      it "assigns the requested animal as @animal" do
        Animal.stub(:find) { mock_animal(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:animal).should be(mock_animal)
      end

      it "redirects to the animal" do
        Animal.stub(:find) { mock_animal(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(animal_url(mock_animal))
      end
    end

    describe "with invalid params" do
      it "assigns the animal as @animal" do
        Animal.stub(:find) { mock_animal(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:animal).should be(mock_animal)
      end

      it "re-renders the 'edit' template" do
        Animal.stub(:find) { mock_animal(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested animal" do
      Animal.stub(:find).with("37") { mock_animal }
      mock_animal.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the animales list" do
      Animal.stub(:find) { mock_animal }
      delete :destroy, :id => "1"
      response.should redirect_to(animales_url)
    end
  end

end
