# encoding: utf-8
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AnimalesController do    

  describe "GET show" do
    
    before(:each) do
      @animal = Factory.stub(:animal)
    end
    
    it "asigna el animal buscado a @animal" do
      Animal.stub(:find).with("37", {:include => :fotos}) { @animal }
      get :show, :id => "37"
      assigns(:animal).should be(@animal)
    end
  end

  describe "POST create" do
    
    before(:each) do
      @animal = Factory.stub(:animal)
      usuario = Factory(:usuario)
      usuario.confirm! 
      sign_in(usuario)
    end
    
    describe "con parámetros válidos" do
      
      before(:each) do
        @animal.stub(:save).and_return(true)
      end
      
      it "asigna un nuevo animal a @animal" do
        Animal.stub(:new).with('correct' => 'params') { @animal }
        
        @animal.should_receive(:aplica_geo).with({"lat" => "19.45", "lon" => "-99.23"})
        post :create, :animal => {'correct' => 'params'}, :coordenadas => {:lat => "19.45", :lon => "-99.23"}
        assigns(:animal).should be(@animal)
      end

      it "redirecciona al recién creado animal" do
        Animal.stub(:new) { @animal }
        @animal.stub(:aplica_geo)
        
        post :create, :animal => {}, :coordenadas => {}
        response.should redirect_to(animal_url(@animal))
      end
    end

    describe "with invalid params" do
      
      before(:each) do
        @animal.stub(:save).and_return(false)
      end
      
      it "assigns a newly created but unsaved animal as @animal" do
        Animal.stub(:new).with('bad' => 'params') { @animal }
        post :create, :animal => {'bad' => 'params'}, :coordenadas => {}
        assigns(:animal).should be(@animal)
      end

      it "re-renders the 'new' template" do
        Animal.stub(:new) { @animal }
        post :create, :animal => {}, :coordenadas => {}
        response.should render_template("new")
      end
    end
  end

end
